
known_col_types:
  pitch_type: STRING
  game_date: DATE
  release_speed: FLOAT64
  release_pos_x: FLOAT64
  release_pos_z: FLOAT64
  batter: INT64
  pitcher: INT64
  events: STRING
  description: STRING
  zone: FLOAT64
  hit_location: INT64
  bb_type: STRING
  pfx_x: FLOAT64
  pfx_z: FLOAT64
  plate_x: FLOAT64
  plate_z: FLOAT64
  on_3b: INT64
  on_2b: INT64
  on_1b: INT64
  hc_x: FLOAT64
  hc_y: FLOAT64
  vx0: FLOAT64
  vy0: FLOAT64
  vz0: FLOAT64
  ax: FLOAT64
  ay: FLOAT64
  az: FLOAT64
  sz_top: FLOAT64
  sz_bot: FLOAT64
  hit_distance_sc: INT64
  launch_speed: FLOAT64
  launch_angle: INT64
  effective_speed: FLOAT64
  release_spin_rate: INT64
  release_extension: FLOAT64
  release_pos_y: FLOAT64
  estimated_ba_using_speedangle: FLOAT64
  estimated_woba_using_speedangle: FLOAT64
  woba_value: FLOAT64
  woba_denom: INT64
  babip_value: INT64
  iso_value: INT64
  launch_speed_angle: INT64
  pitch_name: STRING
  if_fielding_alignment: STRING
  of_fielding_alignment: STRING
  spin_axis: INT64
  delta_home_win_exp: FLOAT64
  delta_run_exp: FLOAT64
  delta_pitcher_run_exp: FLOAT64
  bat_speed: FLOAT64
  swing_length: FLOAT64
  estimated_slg_using_speedangle: FLOAT64
  hyper_speed: FLOAT64
  home_win_exp: FLOAT64
  bat_win_exp: FLOAT64
  batter_days_until_next_game: INT64
  api_break_z_with_gravity: FLOAT64
  api_break_x_arm: FLOAT64
  api_break_x_batter_in: FLOAT64
  arm_angle: FLOAT64
  attack_angle: FLOAT64
  attack_direction: FLOAT64
  swing_path_tilt: FLOAT64
  intercept_ball_minus_batter_pos_x_inches: FLOAT64
  intercept_ball_minus_batter_pos_y_inches: FLOAT64



