statcast:
  base_urls:
    mlb: "https://baseballsavant.mlb.com/statcast_search/csv"
    milb: "https://baseballsavant.mlb.com/statcast-search-minors/csv"

  headers:
    mlb:
      User-Agent: "Mozilla/5.0"
      Referer: "https://baseballsavant.mlb.com/statcast_search"
      Connection: "close"
    milb:
      User-Agent: "Mozilla/5.0"
      Referer: "https://baseballsavant.mlb.com/statcast-search-minors"
      Connection: "close"

  params:
    all: "true"
    type: "details"

gcp:
  project_id: crzzpy
  dataset_id: test
  table_prefix: statcast

logging:
  level: INFO
  log_file: logs/statcast.log
  console_format: "%(log_color)s[%(asctime)s] [%(levelname)s] [%(name)s:%(funcName)s] %(message)s"
  file_format: "[%(asctime)s] [%(levelname)s] [%(name)s:%(funcName)s] %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  log_colors:
    DEBUG: cyan
    INFO: green
    WARNING: yellow
    ERROR: red
    CRITICAL: bold_red



